### PR TITLE
Update version of nfsrods to version 2.1.0

### PR DESCRIPTION
**Pull request by jbeal-work**
I believe nfsrods 1.0.0 does not build because of the change in dependency which is fixed in master. 

This is the minimal change that allows nfsrods docker image to build. I note that the Dockerfile in the nfsrods repo is significantly different however this one is based on 18.04 rather than 16.04 so pulling the whole Dockerfile over feels like a retrograde step.

### CODE REVIEW

**Comment by jbeal-work** [comment]
I am setting this to a work in progress as I think a number of other things may need changing as well.

**Comment by trel** [comment]
Thanks - yes, we have been heads down with 4.2.9 getting out the door.   We'll definitely shift attention to irods_demo before too long and get it back up to speed.

**Comment by trel** [comment]
NFSRODS 2.1.0 is out - will be bumping this soon.

**Comment by alanking** [comment]
We are about to rework this entire project (see #29). Should we close this in favor of a new issue for adding NFSRODS, @trel?

**Comment by korydraughn** [comment]
Yes. We've learned a lot since this repo was last touched and iRODS is much better too.

The rework of this repo will resolve all known issues.

**Comment by trel** [comment]
Yes, please.    Close once #29 lands.

**Pull request closed without merging**
