### PR TITLE
431 and http api

### PR DESCRIPTION
**Pull request by trel**

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Looks correct.

Are we planning to squash or add issue numbers to the last three commits?

**Comment by trel** [comment]
certainly can - i'll make and link a couple more issues.

**Comment by trel** [comment]
done - please confirm.

**Review by korydraughn — APPROVED** [review]
Looks good.

Haven't tried launching it, but the changes make sense.

**Comment by trel** [comment]
okay, merging - can always tweak more later.

**Pull request merged**
