### PR TITLE
[#73] Make iRODS provider write messages to syslog

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
pretty sure we want the stdout to go back to the docker daemon... so... i think i vote -1 on this?

**Comment by trel** [comment]
this is the reason for keeping the server in 'user' mode, or the foreground...
```
su irods -c 'bash -c "./irodsServer -u"'
```

**Comment by trel** [comment]
so we can close this - without merging?

**Comment by korydraughn** [comment]
Yes. This can be closed.

**Pull request closed without merging**
